package NineMenMorris;


import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author markj
 */
public class NineMenMorris extends javax.swing.JFrame {
    public int counter =1;
    /**
     * Creates new form NineMenMorris
     */
    public NineMenMorris() {
        initComponents();
        p1Turn.setVisible(true);
        p2Turn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a2 = new javax.swing.JToggleButton();
        d2 = new javax.swing.JToggleButton();
        e2 = new javax.swing.JToggleButton();
        b2 = new javax.swing.JToggleButton();
        c2 = new javax.swing.JToggleButton();
        h2 = new javax.swing.JToggleButton();
        g2 = new javax.swing.JToggleButton();
        f2 = new javax.swing.JToggleButton();
        d1 = new javax.swing.JToggleButton();
        e1 = new javax.swing.JToggleButton();
        d = new javax.swing.JToggleButton();
        e = new javax.swing.JToggleButton();
        b1 = new javax.swing.JToggleButton();
        b = new javax.swing.JToggleButton();
        g1 = new javax.swing.JToggleButton();
        g = new javax.swing.JToggleButton();
        f = new javax.swing.JToggleButton();
        a = new javax.swing.JToggleButton();
        c = new javax.swing.JToggleButton();
        h = new javax.swing.JToggleButton();
        f1 = new javax.swing.JToggleButton();
        h1 = new javax.swing.JToggleButton();
        c1 = new javax.swing.JToggleButton();
        a1 = new javax.swing.JToggleButton();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p1Turn = new javax.swing.JLabel();
        p2Turn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        turnCounter1 = new javax.swing.JLabel();
        turnCounter2 = new javax.swing.JLabel();
        reset = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nine Men's Morris");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(null);

        a2.setBackground(new java.awt.Color(0, 0, 0));
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        getContentPane().add(a2);
        a2.setBounds(130, 140, 35, 35);

        d2.setBackground(new java.awt.Color(0, 0, 0));
        d2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d2ActionPerformed(evt);
            }
        });
        getContentPane().add(d2);
        d2.setBounds(130, 200, 35, 35);

        e2.setBackground(new java.awt.Color(0, 0, 0));
        e2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e2ActionPerformed(evt);
            }
        });
        getContentPane().add(e2);
        e2.setBounds(260, 200, 35, 35);

        b2.setBackground(new java.awt.Color(0, 0, 0));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(200, 140, 35, 35);

        c2.setBackground(new java.awt.Color(0, 0, 0));
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        getContentPane().add(c2);
        c2.setBounds(260, 140, 35, 35);

        h2.setBackground(new java.awt.Color(0, 0, 0));
        h2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h2ActionPerformed(evt);
            }
        });
        getContentPane().add(h2);
        h2.setBounds(260, 260, 35, 35);

        g2.setBackground(new java.awt.Color(0, 0, 0));
        g2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g2ActionPerformed(evt);
            }
        });
        getContentPane().add(g2);
        g2.setBounds(200, 260, 35, 35);

        f2.setBackground(new java.awt.Color(0, 0, 0));
        f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2ActionPerformed(evt);
            }
        });
        getContentPane().add(f2);
        f2.setBounds(130, 260, 35, 35);

        d1.setBackground(new java.awt.Color(0, 0, 0));
        d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1ActionPerformed(evt);
            }
        });
        getContentPane().add(d1);
        d1.setBounds(70, 200, 35, 35);

        e1.setBackground(new java.awt.Color(0, 0, 0));
        e1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e1ActionPerformed(evt);
            }
        });
        getContentPane().add(e1);
        e1.setBounds(320, 200, 35, 35);

        d.setBackground(new java.awt.Color(0, 0, 0));
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        getContentPane().add(d);
        d.setBounds(10, 200, 35, 35);

        e.setBackground(new java.awt.Color(0, 0, 0));
        e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eActionPerformed(evt);
            }
        });
        getContentPane().add(e);
        e.setBounds(380, 200, 35, 35);

        b1.setBackground(new java.awt.Color(0, 0, 0));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(200, 70, 35, 35);

        b.setBackground(new java.awt.Color(0, 0, 0));
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        getContentPane().add(b);
        b.setBounds(200, 10, 35, 35);

        g1.setBackground(new java.awt.Color(0, 0, 0));
        g1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g1ActionPerformed(evt);
            }
        });
        getContentPane().add(g1);
        g1.setBounds(200, 320, 35, 35);

        g.setBackground(new java.awt.Color(0, 0, 0));
        g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gActionPerformed(evt);
            }
        });
        getContentPane().add(g);
        g.setBounds(200, 380, 35, 35);

        f.setBackground(new java.awt.Color(0, 0, 0));
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });
        getContentPane().add(f);
        f.setBounds(10, 380, 35, 35);

        a.setBackground(new java.awt.Color(0, 0, 0));
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        getContentPane().add(a);
        a.setBounds(10, 10, 35, 35);

        c.setBackground(new java.awt.Color(0, 0, 0));
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        getContentPane().add(c);
        c.setBounds(380, 10, 35, 35);

        h.setBackground(new java.awt.Color(0, 0, 0));
        h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hActionPerformed(evt);
            }
        });
        getContentPane().add(h);
        h.setBounds(380, 380, 35, 35);

        f1.setBackground(new java.awt.Color(0, 0, 0));
        f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f1ActionPerformed(evt);
            }
        });
        getContentPane().add(f1);
        f1.setBounds(70, 320, 35, 35);

        h1.setBackground(new java.awt.Color(0, 0, 0));
        h1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h1ActionPerformed(evt);
            }
        });
        getContentPane().add(h1);
        h1.setBounds(320, 320, 35, 35);

        c1.setBackground(new java.awt.Color(0, 0, 0));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1);
        c1.setBounds(320, 70, 35, 35);

        a1.setBackground(new java.awt.Color(0, 0, 0));
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        getContentPane().add(a1);
        a1.setBounds(70, 70, 35, 35);

        p1.setBackground(new java.awt.Color(0, 0, 255));
        p1.setText("Player 1");
        getContentPane().add(p1);
        p1.setBounds(6, 430, 70, 16);

        p2.setBackground(new java.awt.Color(255, 0, 0));
        p2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        p2.setText("Player 2");
        getContentPane().add(p2);
        p2.setBounds(360, 430, 50, 16);

        p1Turn.setText("Your Turn");
        getContentPane().add(p1Turn);
        p1Turn.setBounds(10, 450, 100, 16);

        p2Turn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        p2Turn.setText("Your Turn");
        getContentPane().add(p2Turn);
        p2Turn.setBounds(320, 450, 100, 16);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\markj\\Documents\\Untitled-2.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 410, 410);

        turnCounter1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        turnCounter1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        turnCounter1.setText("•••••••••");
        getContentPane().add(turnCounter1);
        turnCounter1.setBounds(60, 430, 110, 10);

        turnCounter2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        turnCounter2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        turnCounter2.setText("•••••••••");
        getContentPane().add(turnCounter2);
        turnCounter2.setBounds(250, 430, 110, 10);

        jMenu1.setText("File");

        jMenuItem1.setText("Reset");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        reset.add(jMenu1);

        setJMenuBar(reset);

        setSize(new java.awt.Dimension(438, 540));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        setBG(a);
    }//GEN-LAST:event_aActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        setBG(b);
    }//GEN-LAST:event_bActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        setBG(c);
    }//GEN-LAST:event_cActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        setBG(d);
    }//GEN-LAST:event_dActionPerformed

    private void eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eActionPerformed
        setBG(e);
    }//GEN-LAST:event_eActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
        setBG(f);
    }//GEN-LAST:event_fActionPerformed

    private void gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gActionPerformed
        setBG(g);
    }//GEN-LAST:event_gActionPerformed

    private void hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hActionPerformed
        setBG(h);
    }//GEN-LAST:event_hActionPerformed

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        setBG(a1);
    }//GEN-LAST:event_a1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        setBG(b1);
    }//GEN-LAST:event_b1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        setBG(c1);
    }//GEN-LAST:event_c1ActionPerformed

    private void d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1ActionPerformed
        setBG(d1);
    }//GEN-LAST:event_d1ActionPerformed

    private void e1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e1ActionPerformed
        setBG(e1);
    }//GEN-LAST:event_e1ActionPerformed

    private void f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f1ActionPerformed
        setBG(f1);
    }//GEN-LAST:event_f1ActionPerformed

    private void h1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h1ActionPerformed
        setBG(h1);
    }//GEN-LAST:event_h1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        setBG(b2);
    }//GEN-LAST:event_b2ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        setBG(c2);
    }//GEN-LAST:event_c2ActionPerformed

    private void d2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d2ActionPerformed
        setBG(d2);
    }//GEN-LAST:event_d2ActionPerformed

    private void e2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e2ActionPerformed
        setBG(e2);
    }//GEN-LAST:event_e2ActionPerformed

    private void f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2ActionPerformed
        setBG(f2);
    }//GEN-LAST:event_f2ActionPerformed

    private void g2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g2ActionPerformed
        setBG(g2);
    }//GEN-LAST:event_g2ActionPerformed

    private void h2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h2ActionPerformed
        setBG(h2);
    }//GEN-LAST:event_h2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        reset();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void g1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g1ActionPerformed
        // TODO add your handling code here:
        setBG(g1);
    }//GEN-LAST:event_g1ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        setBG(a2);
    }//GEN-LAST:event_a2ActionPerformed

    public void setBG (JToggleButton var){
        if (counter <= 18){
            if (counter % 2 == 0){
                var.setBackground(Color.blue);
                p1Turn.setVisible(true);
                p2Turn.setVisible(false);
                String temp = turnCounter2.getText();
                String temp1 = "";
                for (int x = 0; x < temp.length() - 1; x++){
                    temp1+=temp.charAt(x);
                }
                turnCounter2.setText(temp1);
            } else {
                var.setBackground(Color.red);
                p1Turn.setVisible(false);
                p2Turn.setVisible(true);
                String temp = turnCounter1.getText();
                String temp1 = "";
                for (int x = 0; x < temp.length() - 1; x++){
                    temp1+=temp.charAt(x);
                }
                turnCounter1.setText(temp1);
            }
            counter++;
        }
    }
    
    public void reset(){
        counter = 1;
        a.setBackground(Color.black);
        b.setBackground(Color.black);
        c.setBackground(Color.black);
        d.setBackground(Color.black);
        e.setBackground(Color.black);
        f.setBackground(Color.black);
        g.setBackground(Color.black);
        h.setBackground(Color.black);
        a1.setBackground(Color.black);
        b1.setBackground(Color.black);
        c1.setBackground(Color.black);
        d1.setBackground(Color.black);
        e1.setBackground(Color.black);
        f1.setBackground(Color.black);
        g1.setBackground(Color.black);
        h1.setBackground(Color.black);
        a2.setBackground(Color.black);
        b2.setBackground(Color.black);
        c2.setBackground(Color.black);
        d2.setBackground(Color.black);
        e2.setBackground(Color.black);
        f2.setBackground(Color.black);
        g2.setBackground(Color.black);
        h2.setBackground(Color.black);
        p1Turn.setVisible(true);
        p2Turn.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NineMenMorris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NineMenMorris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NineMenMorris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NineMenMorris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NineMenMorris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton a;
    private javax.swing.JToggleButton a1;
    private javax.swing.JToggleButton a2;
    private javax.swing.JToggleButton b;
    private javax.swing.JToggleButton b1;
    private javax.swing.JToggleButton b2;
    private javax.swing.JToggleButton c;
    private javax.swing.JToggleButton c1;
    private javax.swing.JToggleButton c2;
    private javax.swing.JToggleButton d;
    private javax.swing.JToggleButton d1;
    private javax.swing.JToggleButton d2;
    private javax.swing.JToggleButton e;
    private javax.swing.JToggleButton e1;
    private javax.swing.JToggleButton e2;
    private javax.swing.JToggleButton f;
    private javax.swing.JToggleButton f1;
    private javax.swing.JToggleButton f2;
    private javax.swing.JToggleButton g;
    private javax.swing.JToggleButton g1;
    private javax.swing.JToggleButton g2;
    private javax.swing.JToggleButton h;
    private javax.swing.JToggleButton h1;
    private javax.swing.JToggleButton h2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p1Turn;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p2Turn;
    private javax.swing.JMenuBar reset;
    private javax.swing.JLabel turnCounter1;
    private javax.swing.JLabel turnCounter2;
    // End of variables declaration//GEN-END:variables
}
