/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OrderTakerV1;

/**
 *
 * @author markj
 */
public class SimpleOrderTaker_Main extends javax.swing.JFrame {
    double sinigang, adobo, tinola, igado, sisig;
    double icedTea, coke, pineJuice;
    double chocoCake, bukoPan, fruitCream;
    double chickNug, burFries, dogSand;
    /**
     * Creates new form SimpleOrderTaker
     */
    public SimpleOrderTaker_Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Chickenjoy = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        md1 = new javax.swing.JToggleButton();
        md2 = new javax.swing.JToggleButton();
        md4 = new javax.swing.JToggleButton();
        md5 = new javax.swing.JToggleButton();
        md3 = new javax.swing.JToggleButton();
        mdprice = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        dr1 = new javax.swing.JToggleButton();
        dr2 = new javax.swing.JToggleButton();
        dr3 = new javax.swing.JToggleButton();
        drprice = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ds1 = new javax.swing.JToggleButton();
        ds2 = new javax.swing.JToggleButton();
        ds3 = new javax.swing.JToggleButton();
        dsprice = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        ap1 = new javax.swing.JToggleButton();
        ap2 = new javax.swing.JToggleButton();
        ap3 = new javax.swing.JToggleButton();
        apprice = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        md1.setText("Sinigang");
        md1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md1ActionPerformed(evt);
            }
        });

        md2.setText("Igado");
        md2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md2ActionPerformed(evt);
            }
        });

        md4.setText("Adobo");
        md4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md4ActionPerformed(evt);
            }
        });

        md5.setText("Sisig");
        md5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md5ActionPerformed(evt);
            }
        });

        md3.setText("Tinola");
        md3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md3ActionPerformed(evt);
            }
        });

        mdprice.setBorder(javax.swing.BorderFactory.createTitledBorder("Price: "));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mdprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(md1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(md4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(md3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(md2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(md5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(md1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(md4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(md2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(md5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(md3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(mdprice, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Chickenjoy.addTab("Main Dishes", jPanel2);

        dr1.setText("Coke");
        dr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dr1ActionPerformed(evt);
            }
        });

        dr2.setText("Iced Tea");
        dr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dr2ActionPerformed(evt);
            }
        });

        dr3.setText("Pineapple Juice");
        dr3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dr3ActionPerformed(evt);
            }
        });

        drprice.setBorder(javax.swing.BorderFactory.createTitledBorder("Price: "));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(dr1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dr3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dr2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(drprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dr1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dr3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dr2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(drprice, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Chickenjoy.addTab("Drinks", jPanel3);

        ds1.setText("Chocolate Cake");
        ds1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ds1ActionPerformed(evt);
            }
        });

        ds2.setText("Fruit Ice Cream");
        ds2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ds2ActionPerformed(evt);
            }
        });

        ds3.setText("Buko Pandan");
        ds3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ds3ActionPerformed(evt);
            }
        });

        dsprice.setBorder(javax.swing.BorderFactory.createTitledBorder("Price: "));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(ds1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ds3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ds2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(dsprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ds1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ds3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ds2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(dsprice, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Chickenjoy.addTab("Desserts", jPanel4);

        ap1.setText("Chicken Nuggets");
        ap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap1ActionPerformed(evt);
            }
        });

        ap2.setText("Burger and Fries");
        ap2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap2ActionPerformed(evt);
            }
        });

        ap3.setText("Hotdog Sandwich");
        ap3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap3ActionPerformed(evt);
            }
        });

        apprice.setBorder(javax.swing.BorderFactory.createTitledBorder("Price: "));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(ap1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ap3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ap2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(apprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ap1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ap3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ap2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(apprice, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Chickenjoy.addTab("Appetizers", jPanel5);

        jButton1.setText("Check Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Chickenjoy)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Chickenjoy, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SimpleOrderTaker_CheckOutPage go = new SimpleOrderTaker_CheckOutPage();
        go.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void md3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md3ActionPerformed
        // TODO add your handling code here:
        if (md3.isSelected()){
            mdprice.setText("219.00");
            tinola = 219.00;
            
        } else {
            mdprice.setText("");
        }
    }//GEN-LAST:event_md3ActionPerformed

    private void md5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md5ActionPerformed
        // TODO add your handling code here:
        if (md5.isSelected()){
            mdprice.setText("169.00");
            sisig = 169.00;
        } else {
            mdprice.setText("");
        }
    }//GEN-LAST:event_md5ActionPerformed

    private void md4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md4ActionPerformed
        // TODO add your handling code here:
        if (md4.isSelected()){
            mdprice.setText("199.00");
            adobo = 199.00;
        } else {
            mdprice.setText("");
        }
    }//GEN-LAST:event_md4ActionPerformed

    private void md2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md2ActionPerformed
        // TODO add your handling code here:
        if (md2.isSelected()){
            mdprice.setText("179.00");
            igado = 179.00;
        } else {
            mdprice.setText("");
        }
    }//GEN-LAST:event_md2ActionPerformed

    private void md1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md1ActionPerformed
        // TODO add your handling code here:
        if (md1.isSelected()){
            mdprice.setText("189.00");
            sinigang = 189.00;
        } else {
            mdprice.setText("");
        }
    }//GEN-LAST:event_md1ActionPerformed

    private void dr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dr1ActionPerformed
        // TODO add your handling code here:
        if (dr1.isSelected()){
            drprice.setText("35.00");
            coke = 35.00;
        } else {
            drprice.setText("");
        }
    }//GEN-LAST:event_dr1ActionPerformed

    private void dr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dr2ActionPerformed
        // TODO add your handling code here:
        if (dr2.isSelected()){
            drprice.setText("25.00");
            icedTea = 25.00;
        } else {
            drprice.setText("");
        }
    }//GEN-LAST:event_dr2ActionPerformed

    private void dr3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dr3ActionPerformed
        // TODO add your handling code here:
        if (dr3.isSelected()){
            drprice.setText("45.00");
            pineJuice = 45.00;
        } else {
            drprice.setText("");
        }
    }//GEN-LAST:event_dr3ActionPerformed

    private void ds1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ds1ActionPerformed
        // TODO add your handling code here:
        if (ds1.isSelected()){
            dsprice.setText("70.00");
            chocoCake = 70.00;
        } else {
            dsprice.setText("");
        }
    }//GEN-LAST:event_ds1ActionPerformed

    private void ds2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ds2ActionPerformed
        // TODO add your handling code here:
        if (ds2.isSelected()){
            dsprice.setText("110.00");
            fruitCream = 110.00;
        } else {
            dsprice.setText("");
        }
    }//GEN-LAST:event_ds2ActionPerformed

    private void ds3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ds3ActionPerformed
        // TODO add your handling code here:
        if (ds3.isSelected()){
            dsprice.setText("80.00");
            bukoPan = 80.00;
        } else {
            dsprice.setText("");
        }
    }//GEN-LAST:event_ds3ActionPerformed

    private void ap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap1ActionPerformed
        // TODO add your handling code here:
        if (ap1.isSelected()){
            apprice.setText("119.00");
            chickNug = 119.00;
        } else {
            apprice.setText("");
        }
    }//GEN-LAST:event_ap1ActionPerformed

    private void ap2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap2ActionPerformed
        // TODO add your handling code here:
        if (ap2.isSelected()){
            apprice.setText("90.00");
            burFries = 90.00;
        } else {
            apprice.setText("");
        }
    }//GEN-LAST:event_ap2ActionPerformed

    private void ap3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap3ActionPerformed
        // TODO add your handling code here:
        if (ap3.isSelected()){
            apprice.setText("50.00");
            dogSand = 50.00;
        } else {
            apprice.setText("");
        }
    }//GEN-LAST:event_ap3ActionPerformed
    int x = 27, y = 56;
    int total;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleOrderTaker_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleOrderTaker_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleOrderTaker_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleOrderTaker_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleOrderTaker_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Chickenjoy;
    private javax.swing.JToggleButton ap1;
    private javax.swing.JToggleButton ap2;
    private javax.swing.JToggleButton ap3;
    private javax.swing.JLabel apprice;
    private javax.swing.JToggleButton dr1;
    private javax.swing.JToggleButton dr2;
    private javax.swing.JToggleButton dr3;
    private javax.swing.JLabel drprice;
    private javax.swing.JToggleButton ds1;
    private javax.swing.JToggleButton ds2;
    private javax.swing.JToggleButton ds3;
    private javax.swing.JLabel dsprice;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JToggleButton md1;
    private javax.swing.JToggleButton md2;
    private javax.swing.JToggleButton md3;
    private javax.swing.JToggleButton md4;
    private javax.swing.JToggleButton md5;
    private javax.swing.JLabel mdprice;
    // End of variables declaration//GEN-END:variables
}
